theme: minima
title: KalyanV
author: &anchor_author "Kalyan Vedala"
header_pages:
    - projects.md
    - contact.html
    - about.md
defaults:
  - scope:
      path: ""
    values:
      author: *anchor_author
disqus:
    shortname: kalyanvblog
description: I blog here about software development topics related to projects and tools I happen to be working on currently.
github_username: vedala
twitter_username: skvedala
rss: rss
google_analytics: UA-93095447-2
action_url: https://hooks.zapier.com/hooks/catch/3967548/oyef7os/
thank_you_page: thank_you.html
