theme: minima
title: KalyanV
author: "Kalyan Vedala"
header_pages:
    - projects.md
    - about.md
disqus:
    shortname: kalyanvblog
description: I blog here about software development topics related to projects and tools I happen to be working on currently.
github_username: vedala
twitter_username: skvedala
rss: rss
