theme: minima
title: KalyanV
header_pages:
    - projects.md
    - about.md
defaults:
  - scope:
      path: ""
    values:
      author: "Kalyan Vedala"
disqus:
    shortname: kalyanvblog
description: I blog here about software development topics related to projects and tools I happen to be working on currently.
